language: php

php:
  - 7.3

before_script:
  - pip install --user codecov
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-xml coverage.xml

after_success:
  - codecov