<?php

namespace unit;

use http\Client;
use PHPUnit\Framework\TestCase;
use seosazi\PathConverter\ConvertToAbsolutePath;

class ConvertToAbsolutePathTest extends TestCase
{
    /** @var ConvertToAbsolutePath */
    private $address;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setAddress(
            new ConvertToAbsolutePath()
        );
    }

    /**
     * @dataProvider dataForTestUpToLastDir
     * @param $path
     * @param $result
     */
    public function testUpToLastDir($path, $result)
    {
        $this->assertSame($this->getAddress()->upToLastDir($path), $result);
    }

    public function dataForTestUpToLastDir()
    {
        return [
            'page path with file name'  => [
                'http://example.com/some/fake/path/page.html',
                'http://example.com/some/fake/path/'
            ],
            'page path with any file name type 1' => [
                'http://example.com/some/fake/',
                'http://example.com/some/fake/'
            ],
            'page path with any file name type 2' => [
                'http://example.com/some/fake',
                'http://example.com/some/'
            ],
            'home page' => [
                'http://example.com',
                'http://example.com/'
            ]
        ];
    }

    /**
     * @dataProvider dataForOnlySitePath
     * @param $path
     * @param $result
     */
    public function testOnlySitePath($path, $result)
    {
        $this->assertSame($this->getAddress()->onlySitePath($path), $result);
    }

    public function dataForOnlySitePath()
    {
        return [
            'page path with file name'  => [
                'http://example.com/some/fake/path/page.html',
                'http://example.com'
            ],
            'page path with any file name type 1' => [
                'http://example.com/some/fake/',
                'http://example.com'
            ],
            'page path with any file name type 2' => [
                'http://example.com/some/fake',
                'http://example.com'
            ],
            'home page 1' => [
                'http://example.com',
                'http://example.com'
            ],
            'home page 2' => [
                'example.com/some/fake',
                ''
            ]
        ];
    }


    /**
     * @dataProvider dataForConvert
     * @param $pagePath
     * @param $baseTag
     * @param $path
     * @param $result
     */
    public function testConvert($pagePath, $baseTag, $path, $result)
    {
        if (isset($pagePath)) {
            $this->getAddress()->setPagePath($pagePath);
        }
        if (isset($baseTag)) {
            $this->getAddress()->setBaseTag($baseTag);
        }
        $this->assertSame($this->getAddress()->convert($path), $result);
    }

    public function dataForConvert()
    {
        return [
            'normal page with base'  => [
                'https://www.php.net/manual/en/function.parse-url.php',
                'https://www.php.net/manual/en/function.parse-url.php',
                '/images/notes-add@2x.png',
                'https://www.php.net/images/notes-add@2x.png'
            ],
            'normal page without base'  => [
                'https://kafshnice.ir/product-category/shoe/for-men/',
                null,
                'https://kafshnice.ir/wp-content/uploads/2020/01/2020-01-23_6-11-45-99x75.png',
                'https://kafshnice.ir/wp-content/uploads/2020/01/2020-01-23_6-11-45-99x75.png'
            ],
            'normal page without base 2'  => [
                'https://roadmap.sh/backend',
                null,
                '/_next/static/hxwb-QfpHEYaFAmytdA9D/pages/%5Broadmap%5D.js',
                'https://roadmap.sh/_next/static/hxwb-QfpHEYaFAmytdA9D/pages/%5Broadmap%5D.js'
            ],
            'normal page without base 3'  => [
                'https://bastam.bankmellat.ir/bastam/shahab_service',
                null,
                '/bastam/resources/images/browserSupport/war_icon.png',
                'https://bastam.bankmellat.ir/bastam/resources/images/browserSupport/war_icon.png'
            ]
        ];
    }

    /**
     * @return ConvertToAbsolutePath
     */
    public function getAddress(): ConvertToAbsolutePath
    {
        return $this->address;
    }

    /**
     * @param ConvertToAbsolutePath $address
     */
    public function setAddress(ConvertToAbsolutePath $address): void
    {
        $this->address = $address;
    }
}
